[project]
name = "nft-guestbook"
description = "NFT Guestbook DApp on Stacks blockchain"
authors = ["Your Name"]
telemetry = true
cache_dir = "./.cache"

[contracts.nft-guestbook]
path = "contracts/nft-guestbook.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
seed = 12345

[wallets.deployer]
mnemonic = "tiny illegal rapid illegal suspect forget galaxy exist metal physics prefer mango"
balance = 1000000000000000
address = "ST1PQHQKV0RJXZYYVE4PXCDBNCZQJF6M6W7G6M6C"

[wallets.wallet_1]
mnemonic = "expose appeal spray actual moment top monkey pipe solar shy expose edge"
balance = 100000000000000
address = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2Z2EQ5AI"

[wallets.wallet_2]
mnemonic = "hold excess custom grief survey egg absent mention strike host sauce rate"
balance = 100000000000000
address = "ST2CYB5N59D4FHGK6E6DFL7Q3T2D6SR5CT6D2A2P"

[wallets.wallet_3]
mnemonic = "illegal october arrow major voice milk energy grid motor cage become fan"
balance = 100000000000000
address = "ST3J2PVMMM2D27EWY424V275WQ5X6XRAKBJQNGTK"

[wallets.wallet_4]
mnemonic = "letter advice cage absurd amount doctor acoustic print raw smile palace"
balance = 100000000000000
address = "ST3NB4FKQD6XWHJF5NZV4F5J2K2VF51K4S5WE6YF"

[env.testnet]
network = "testnet"
node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
bitcoin_node_rpc_address = "bitcoin://blockstream.info:433"

[env.mainnet]
network = "mainnet"
node_rpc_address = "https://stacks-node-api.mainnet.stacks.co"
bitcoin_node_rpc_address = "bitcoin://blockstream.info:8333"
